### ISSUE TITLE
hostname substitution

### ISSUE THREAD

**Issue by micsor-norlys** [thorsager/mockdev#8]
Add the the template function on response `headers` and `body` to allow for _hostname_ substitution. This will be very helpful when building URLs in responses. ex `Location` headers.

**Comment by thorsager** [comment]
This could perhaps be done by adding a `base-url` option to the http configuration

**Comment by micsor-norlys** [comment]
I think perhaps, this could be implemented in a "broader" sense, by adding ex. both runtime-environment and server configuration to the template render process.
